# Using a slim version of Python for efficiency
FROM python:3.11-slim

WORKDIR /app

# Install heavy ML and Celery requirements
COPY requirements-worker.txt .
RUN pip install --no-cache-dir -r requirements-worker.txt

# Create non-root user
RUN useradd -m appuser && chown -R appuser /app

# Copy application and model files
COPY . .
RUN chown -R appuser /app

# Switch to non-root user
USER appuser